# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loadbot < Formula
  desc "Workload database driver"
  homepage "https://github.com/kuzxnia/loadbot"
  version "1.0.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.11/loadbot_1.0.11_darwin_arm64.tar.gz"
      sha256 "4d6929c3cc53cae7f1504fedd65d580e1e54fe92efeacf601711d40245d92b20"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.11/loadbot_1.0.11_darwin_x86_64.tar.gz"
      sha256 "348bf0a868a61148d78819f82dadd99a93a97897c0abea01c83f7bad0e675e8a"

      def install
        bin.install "loadbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.11/loadbot_1.0.11_linux_arm64.tar.gz"
      sha256 "50fc66564d4519d3d4d0eed2999ae2e536f6d63470e6f48d07ebfa3c1840ba96"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.11/loadbot_1.0.11_linux_x86_64.tar.gz"
      sha256 "9c3c9151a58280c80b4f6b0c3918a9a207e89c87f54332468bfbb607dfa50c38"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.11/loadbot_1.0.11_linux_armv7.tar.gz"
      sha256 "a656f70d4545a86628d29c4588ab2592ff3e56deb5d0bce0201c4d2063aa9662"

      def install
        bin.install "loadbot"
      end
    end
  end

  test do
    system "#{bin}/loadbot -v"
  end
end
