# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loadbot < Formula
  desc "Workload database driver"
  homepage "https://github.com/kuzxnia/loadbot"
  version "1.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.8/loadbot_1.0.8_darwin_arm64.tar.gz"
      sha256 "ece75851acb847d407fb921b3de67d31017b4f7759cf9bee89cffcbaba5f637b"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.8/loadbot_1.0.8_darwin_x86_64.tar.gz"
      sha256 "7a95bc1f8748ea0fe05829bd07b6780f497f03404809ad576eafb9fc21547737"

      def install
        bin.install "loadbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.8/loadbot_1.0.8_linux_arm64.tar.gz"
      sha256 "23e0dffd59318d19790a0221644a7aeb9a03d9c4d46232b2012978ec04c18c21"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.8/loadbot_1.0.8_linux_x86_64.tar.gz"
      sha256 "b2e3f83eb51095c81fa225f9bea08a2edcf506f5c88c60d8069a79c3d3b71b68"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.8/loadbot_1.0.8_linux_armv7.tar.gz"
      sha256 "044d35e38a2cbd8383d9e919146761ece35a3b73f3fa653d1cb198dcfe4a0b60"

      def install
        bin.install "loadbot"
      end
    end
  end

  test do
    system "#{bin}/loadbot -v"
  end
end
