# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loadbot < Formula
  desc "Workload database driver"
  homepage "https://github.com/kuzxnia/loadbot"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.1/loadbot_1.0.1_darwin_arm64.tar.gz"
      sha256 "a8613f088cae4a6674c3d8243ccd8294fd2ce5f3ef59d88e485da5bc16895d1a"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.1/loadbot_1.0.1_darwin_x86_64.tar.gz"
      sha256 "749cc33452346d7b088473b6b7c1f1d04feff25294fc423dc65b1074ac2a04cf"

      def install
        bin.install "loadbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.1/loadbot_1.0.1_linux_armv7.tar.gz"
      sha256 "1ae1b0722a75edf2fe39878d0f928cbbea82958bfb81b311b6eeb4187d946cb9"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.1/loadbot_1.0.1_linux_arm64.tar.gz"
      sha256 "52df7b5bbc5de82e0513c74d89886778b905fe7a58d53179563fa7e75641713b"

      def install
        bin.install "loadbot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kuzxnia/loadbot/releases/download/1.0.1/loadbot_1.0.1_linux_x86_64.tar.gz"
      sha256 "a5eb7324818a074a5db2f3aff6d2365e6f9adc2e32e29ce0247f36a301eed417"

      def install
        bin.install "loadbot"
      end
    end
  end

  test do
    system "#{bin}/loadbot -v"
  end
end
